name: CI/CD Release Linux

on:
  release:
    types:
      - published

jobs:
  release-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and package the app
      run: |
        sudo npm install --unsafe-perm=true --allow-root
        npm run build
        electron-builder --linux -p never

    - name: Get app version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master

    - name: Upload AppImage to release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/yang991178/fluent-reader/releases/${{ github.ref }}/assets
        asset_path: ./bin/linux/x64/Fluent Reader-${{ steps.package-version.outputs.current-version }}.AppImage
        asset_name: Fluent.Reader.${{ steps.package-version.outputs.current-version }}.AppImage
        asset_content_type: application/octet-stream
